[32m2023-08-23 00:11:24 +0545[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - bec2b839-8ef1-40bc-9c81-0c255430a57a - 32591 - LOGS_CAPTURED - Started capturing logs in process (pid: 32591).
[32m2023-08-23 00:11:24 +0545[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - bec2b839-8ef1-40bc-9c81-0c255430a57a - 32591 - api__github_commits - STEP_START - Started execution of step "api__github_commits".
[32m2023-08-23 00:11:26 +0545[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - bec2b839-8ef1-40bc-9c81-0c255430a57a - 32591 - api__github_commits - STEP_FAILURE - Execution of step "api__github_commits" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "api__github_commits"::

ValueError: If using all scalar values, you must pass an index

Stack Trace:
  File "/home/kushal/PROJECTS/dagster_github_metrics/dagster-dbt-test-env/lib/python3.10/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/home/kushal/PROJECTS/dagster_github_metrics/dagster-dbt-test-env/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 445, in iterate_with_context
    next_output = next(iterator)
  File "/home/kushal/PROJECTS/dagster_github_metrics/dagster-dbt-test-env/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 125, in gen_from_async_gen
    yield loop.run_until_complete(async_gen.__anext__())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/kushal/PROJECTS/dagster_github_metrics/dagster-dbt-test-env/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 92, in _coerce_async_op_to_async_gen
    result = await awaitable
  File "/home/kushal/PROJECTS/dagster_github_metrics/dagster_github_metrics/assets/api/api_github_commits.py", line 16, in github_commits
    component_top_stories = DataFrame(
  File "/home/kushal/PROJECTS/dagster_github_metrics/dagster-dbt-test-env/lib/python3.10/site-packages/pandas/core/frame.py", line 709, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/home/kushal/PROJECTS/dagster_github_metrics/dagster-dbt-test-env/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 481, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "/home/kushal/PROJECTS/dagster_github_metrics/dagster-dbt-test-env/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 115, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/home/kushal/PROJECTS/dagster_github_metrics/dagster-dbt-test-env/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 645, in _extract_index
    raise ValueError("If using all scalar values, you must pass an index")
[0m
